# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

minimal_mistakes_skin: "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

title: Propaganda for Myself
email: contact@ajin.im
description: >- # this means to ignore newlines until "baseurl:"
  Thoughts tends to fester if you don't air them.
  I'm airing my thoughts here so it wouldn't stink up the house.
twitter_username:
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ajin"
  avatar : "/assets/images/20181027_Deathmask_Frog.jpg"
  bio    : "I got born. I had had. But I've never stop complaining."
  location : "mostly Seoul, South Korea unless trying to not be in England and failing."
  email : contact@ajin.im
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
     url: "mailto:contact@ajin.im"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://mobile.twitter.com/poppypetalmask/"


footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
     url: "mailto:contact@ajin.im"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://mobile.twitter.com/poppypetalmask/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show-date: true
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
